<a href="https://colab.research.google.com/github/Amulya-NRIdegree/Mini-project-/blob/main/Exploring%20The%20Basic%20Of%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy _ numeric python
#Most powerfull package _ library
#Numpy _ Dimensions
#A _ one Dimensional Array
#[A,B] || [A,
         #  B] _ Two Dimensional Array _ Row || column
# Three Dimensional
#Array _ storing manipulating, similar Data type
#Faster than any mathematical functions
# Convincent compared to other packages
# memory efficiency
# support multi dimensional arrays
# speed(numpy operations) > speed (lists operations)
# size (numpy opretions) > size (lists operations)
# memory(numpy)

In [1]:
import numpy as np

In [4]:
# create a numpy array
# 1D array

arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [7]:
# create 2D array _ matrix
arr2D = np.array([
     [1,2,3],[4,5,6]
  ])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [8]:
#creating arrays with default values
allzeros = np.zeros([2,3])
print(allzeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#creating matrix with values of elements as '1'
allones = np.ones([2,3])
print(allones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
#creating matrix with values of elements as 'constant value _ n ~ fill value'
allconstant = np.full([2,3],6)
print(allconstant)

[[6 6 6]
 [6 6 6]]


In [11]:
#create an identity matrix _ I
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
#Identity matrix _ Anii = 1 && Aij = 0
#for all A Belongs to R MxN
#Aij

In [13]:
# creating random matrices
#With 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10, 20,size=(3,3))
print(rand2)

[[0.0570905  0.96036826 0.27656005]
 [0.5814878  0.47985278 0.14195653]
 [0.40307694 0.15861086 0.36603292]]
[[16 11 16]
 [17 11 14]
 [12 19 19]]


In [14]:
# Array Properties
arr = np.array([[1,2,3,4],[1,4,5,6]])
print(arr)

# Shape of array
print(f'\nThe shape of the array is {arr.shape}')

# Size of array
print(f'The size of the array is {arr.size}')

# Datatype of array
print(f'The Data type of the array is {arr.dtype}')

# Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [1 4 5 6]]

The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [15]:
# indexing and slicing

#Access the elements in 1D Array

arr = np.array([1,2,3,4])
print(arr)
print(arr[3])

[1 2 3 4]
4


In [16]:
# slicing the elements

print(arr[0:3])

# Access the element in 2D Array

arr2 = np.array([[1,2,3],[2,3,4]])

print(arr2)

print(arr2[1,1])

print(arr2[0,:])# First row with all columns

print(arr2[:,0])# First column with all rows

[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]
